# https://github.com/wangyoucao577/go-release-action

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release Binary
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "gradlex"
          ldflags: |
            -s -w
            -X 'github.com/jacknic/gradlex/cmd.Version=${{ github.ref_name }}'
            -X 'github.com/jacknic/gradlex/cmd.GitTag=${{ github.ref_name }}'
            -X 'github.com/jacknic/gradlex/cmd.GitCommit=${{ github.sha }}'
            -X 'github.com/jacknic/gradlex/cmd.BuildTime=$(TZ=Asia/Shanghai date +'%Y%m%d %H:%M:%S')'
